
@email = "aurelio_smitha@kuphal-kassulke.test"
@password = "password"


###

# @name register
POST http://localhost:3000/register 
content-type: application/json

{
  "name": "Evan Armstrong III", 
  "email": {{email}}, 
  "password": {{password}}, 
  "password_confirmation": "password"
}

###
# @name login
POST http://localhost:3000/login 
content-type: application/json

{  
  "email": "aurelio_smitha@kuphal-kassulke.test", 
  "password": "password"
}